# Generated by Django 4.0.3 on 2022-04-04 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredients',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='skintype',
            old_name='skin_type',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='ProductDescription',
        ),
    ]
