# Generated by Django 4.0.3 on 2022-03-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='scent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='texture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='usage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='use_image',
        ),
    ]
