# Generated by Django 4.0.3 on 2022-04-04 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_scent_remove_product_texture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'feelings',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='feeling',
        ),
        migrations.CreateModel(
            name='ProductFeelings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.feeling')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'product_feelings',
            },
        ),
    ]
