# Generated by Django 4.0.3 on 2022-04-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_scent_remove_product_texture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredients',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skintype',
            old_name='skin_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productingredient',
            name='squence',
        ),
        migrations.AddField(
            model_name='category',
            name='main_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.ManyToManyField(through='products.ProductSkintype', to='products.skintype'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='major',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
