# Generated by Django 4.0.3 on 2022-04-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_howtouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.RemoveField(
            model_name='productingredient',
            name='squence',
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.ManyToManyField(through='products.ProductSkintype', to='products.skintype'),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='howtouse',
            field=models.JSONField(),
        ),
    ]
