# Generated by Django 4.0.3 on 2022-04-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_feeling_remove_product_feeling_productfeelings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredients',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='skintype',
            old_name='skin_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='productingredient',
            name='squence',
        ),
        migrations.AddField(
            model_name='category',
            name='main_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='feelings',
            field=models.ManyToManyField(through='products.ProductFeelings', to='products.feeling'),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.ManyToManyField(through='products.ProductSkintype', to='products.skintype'),
        ),
        migrations.AddField(
            model_name='productingredient',
            name='major',
            field=models.BooleanField(default=False),
        ),
    ]
