# Generated by Django 4.0.3 on 2022-04-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_ingredients_ingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='url',
        ),
    ]
