# Generated by Django 4.0.3 on 2022-03-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='nomal_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
