# Generated by Django 4.0.3 on 2022-04-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_feeling_remove_product_feeling_productfeelings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feelings',
            field=models.ManyToManyField(through='products.ProductFeelings', to='products.feeling'),
        ),
    ]
