# Generated by Django 4.0.3 on 2022-04-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_ingredients_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='skin_type',
            new_name='skin_types',
        ),
    ]
