# Generated by Django 4.0.3 on 2022-04-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_image_url_productimage_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skintype',
            old_name='skin_type',
            new_name='name',
        ),
    ]
