# Generated by Django 4.0.3 on 2022-04-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_ingredient_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productingredient',
            old_name='main',
            new_name='major',
        ),
    ]
