# Generated by Django 4.0.3 on 2022-04-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_skin_type_product_skin_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.CharField(max_length=2000),
        ),
    ]
